version: "3"
services:
  rest-api:
    #build: ./rest-api
    image: localhost:5000/scproj/rest-api:latest
    command: python api.py #python instead of gunicorn for local dev
    #depends_on:
    #  db:
    #    condition: service_healthy #TODO ????
    volumes:
      - ./rest-api:/api
    environment:
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example1337
      PYTHONUNBUFFERED: 1
    ports:
      - "1337:1337"
    links:
      - db:database
  db:
    expose:
      - "27017"
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example1337