apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  labels:
    app: db
spec:
  accessModes:
    - ReadWriteOnce
  #volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: microk8s-hostpath