apiVersion: v1
kind: Service
metadata:
  name: rest-api
  labels:
    app: rest-api
spec:
  type: NodePort
  ports:
    - name: "rest-api"
      port: 1337
      targetPort: 1337
      nodePort: 30007 # expose this port to outside world. just for testing now as in the real app only web frontend should be open, right?
  selector:
      app: rest-api